### ISSUE TITLE
RobustSingleLinkage doesn't work

### ISSUE THREAD

**Issue by Phlya** [lmcinnes/hdbscan#11]
OK, a bigger issue now... I wanted to play a little with robust single linkage, but seems like it doesn't work:

    clusterer = hdbscan.RobustSingleLinkage(cut=0.125, k=7)
    cluster_labels = clusterer.fit_predict(data)

And I get this:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-87-39b93d0a5ec8> in <module>()
    ----> 1 clusterer = hdbscan.RobustSingleLinkage(cut=0.125, k=7)
          2 cluster_labels = clusterer.fit_predict(data)

    AttributeError: 'module' object has no attribute 'RobustSingleLinkage'

Am I doing something wrong?

**Comment by lmcinnes** [comment]
That's just and accident; I really haven't been playing with RobustSingleLinkage much, so I missed some obvious imports in __init__.py. Fixed now, and if you want to get it working just change the __init__.py in the hdbscan install to be:

from .hdbscan_ import HDBSCAN,  hdbscan
from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage

Good catch again.
