### ISSUE TITLE
import hdbscan error in 0.5

### ISSUE THREAD

**Issue by jc-healy** [lmcinnes/hdbscan#12]
in robust_single_linkage_.py I believe that line 24 should be changed from
from dist_metrics import DistanceMetric 
to
from .dist_metrics import DistanceMetric 
If you're busy I'll spend some time tomorrow morning getting my github working and try a pull request.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3f1c79fb1b69> in <module>()
----> 1 import hdbscan

/Users/jchealy/anaconda/lib/python3.5/site-packages/hdbscan/__init__.py in <module>()
      1 from .hdbscan_ import HDBSCAN,  hdbscan
----> 2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage

/Users/jchealy/anaconda/lib/python3.5/site-packages/hdbscan/robust_single_linkage_.py in <module>()
     22 from ._hdbscan_linkage import single_linkage, mst_linkage_core_cdist, label
     23 from ._hdbscan_boruvka import KDTreeBoruvkaAlgorithm, BallTreeBoruvkaAlgorithm
---> 24 from dist_metrics import DistanceMetric
     25 from ._hdbscan_reachability import mutual_reachability
     26 from .plots import SingleLinkageTree

ImportError: No module named 'dist_metrics'

**Comment by lmcinnes** [comment]
Fixed now.
