### ISSUE TITLE
More windows fun

### ISSUE THREAD

**Issue by jc-healy** [lmcinnes/hdbscan#18]
Ok, I'm trying to get this up and running under windows 7 64-bit via the conda install.

Conda install was had no hitches but upon importing hdbscan I get an error.

import hdbscan
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3f1c79fb1b69> in <module>()
----> 1 import hdbscan

H:\Programs\Anaconda\lib\site-packages\hdbscan\__init__.py in <module>()
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage

H:\Programs\Anaconda\lib\site-packages\hdbscan\hdbscan_.py in <module>()
     27     check_array = check_arrays
     28 
---> 29 from ._hdbscan_linkage import (single_linkage,
     30                                mst_linkage_core,
     31                                mst_linkage_core_pdist,

ImportError: No module named 'hdbscan._hdbscan_linkage

I've got the appropriate .so files here:
 
 Directory of H:\Programs\Anaconda\Lib\site-packages\hdbscan
12/06/2015  10:32 AM    <DIR>          .
12/06/2015  10:32 AM    <DIR>          ..
12/06/2015  10:31 AM                 0 dir
12/03/2015  10:23 PM           315,520 dist_metrics.so
12/03/2015  10:23 PM            24,265 hdbscan_.py
12/03/2015  10:23 PM            26,905 plots.py
12/03/2015  10:23 PM            14,579 robust_single_linkage_.py
12/03/2015  10:23 PM           373,264 _hdbscan_boruvka.so
12/03/2015  10:23 PM           247,144 _hdbscan_linkage.so
12/03/2015  10:23 PM            95,092 _hdbscan_reachability.so
12/03/2015  10:23 PM           324,792 _hdbscan_tree.so
12/03/2015  10:23 PM               118 __init__.py
12/06/2015  10:20 AM    <DIR>          __pycache__
              11 File(s)      1,421,679 bytes
               3 Dir(s)  2,647,232,114,688 bytes free

I'm not a huge windows guys but I'll poke around and see if I can work it out.

**Comment by lmcinnes** [comment]
I would expect that on Windows you should have `dll`'s not `so` files. I take that to mean that something in the platform conversion was not doing all it should have (or, more accurately, I was not using it correctly). It was a first pass following the through the tutorials, but I suspect we need to go through all of this a little more carefully. Perhaps Chris can look at this?

**Comment by lmcinnes** [comment]
Fixed with the move to conda-forge for conda packages.
