### ISSUE TITLE
Fresh linux install: limits.h not found

### ISSUE THREAD

**Issue by jc-healy** [lmcinnes/hdbscan#21]
Hi guys,

I had a minor issue with getting hdbscan to compile on a fresh linux mint install.   I figured I'd document it here in to save other folks a bit of hassle.

The meat of the error looked like:
 `/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory`

This was resolved via:
`sudo apt-get install g++`

**Comment by ricardordb** [comment]
saved my life! thanks!

**Comment by lmcinnes** [comment]
Thanks for documenting this one John!
