### ISSUE TITLE
Different labeling results when using ball tree vs k-d tree for backing structure

### ISSUE THREAD

**Issue by mattfishburn** [lmcinnes/hdbscan#23]
Hi,

Thank you for your work on this library!  I have been playing around with classifying some multivariate normal distributions, and noticed that the library outputs different results for some datasets when using a ball tree as the backing structure versus a k-d tree.  I'm not familiar with classification algorithms, but should the results be different based on the backing data structure?  I have included a set of code below, along with an array of 2D features loadable with numpy, that shows these differences.

numpy version: 1.9.2
hdbscan verison: 0.6.5
scikit-learn version: 0.17

File containing .npy array with features:
[features.zip](https://github.com/lmcinnes/hdbscan/files/119319/features.zip)

Reproduction code, may need to edit 'features.npy' to point to path of unzipped file from above.

    import numpy as np
    import hdbscan
    import matplotlib.pyplot as plt
    
    features = np.load('features.npy')
        
    ballClassifier = hdbscan.HDBSCAN(min_cluster_size=32, gen_min_span_tree = True, algorithm='boruvka_balltree')
    ballClassifier.fit(features)
    ballLabels = ballClassifier.labels_
    
    kdClassifier = hdbscan.HDBSCAN(min_cluster_size=32, gen_min_span_tree = True, algorithm='boruvka_kdtree')
    kdClassifier.fit(features)
    kdLabels = kdClassifier.labels_
    
    plt.figure()
    
    for subIdx, classifier in enumerate([ballClassifier, kdClassifier]):
        labels = classifier.labels_
        plt.subplot(2, 2, 2*subIdx + 1)
        uniqueLabels = sorted(list(set(labels)))
        
        colors = plt.cm.Spectral(np.linspace(0, 1, max( len(uniqueLabels), 6)))
        
        for label, col in zip(uniqueLabels, colors):
            class_member_mask = (labels == label)
        
            xy = features[class_member_mask]
            plt.plot(xy[:, 0], xy[:, 1], '.', markerfacecolor=col,
                    markeredgecolor=col, markersize=1)
    
        plt.subplot(2, 2, 2*subIdx + 2)
        classifier.condensed_tree_.plot()
        
        
    plt.show()

Plot showing the ball tree output (top) vs k-d tree output (bottom):

![hdbscan_ball_vs_kd](https://cloud.githubusercontent.com/assets/14073406/12850120/362b6490-cbf1-11e5-8a2f-590a7fcbb2e0.png)

**Comment by lmcinnes** [comment]
That's a clear bug in the kd-tree output. I'll have to dig into the code and see if I can figure out the issue. Thanks for the actual datasets and code! That will help a lot with debugging this.

**Comment by mattfishburn** [comment]
You are very welcome!  Please let me know if you have any issues with reading the .npy file, I can post the values in a different format.

This issue seems to occur on about 1 out of every 400 datasets that use a similar generating model.

**Comment by lmcinnes** [comment]
I can reproduce the problem from the latest version in pip, but the current repo version seems to work correctly. Hopefully I'll get a 0.7 release out soon, and that may correct the issue.
