### ISSUE TITLE
Extracting the hierarchy

### ISSUE THREAD

**Issue by oligilo** [lmcinnes/hdbscan#24]
I am trying to extract the hierarchy to a pandas dataframe, following the "how HDBSCAN works" notebook, by invoking:
`>>> clusterer.single_linkage_tree_.to_pandas()`
and I get:
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/hdbscan/plots.py", line 520, in to_pandas
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 226, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 363, in _init_dict
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 5158, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 5206, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length

Am I doing something wrong?

It would also be great if there was a numpy array export capability out there in the form of **scipy.cluster.hierarchy.linkage** output; inspecting the above **to_pandas** method suggests that the returned dataframe would be of a different format --if I ever manage to get it right:

`inspect.getmembers(clusterer.single_linkage_tree_.to_pandas)`
> Return a pandas dataframe representation of the single linkage tree.\n\n        Each row of the dataframe corresponds to an edge in the tree.\n        The columns of the dataframe are `parent`, `left_child`, \n        `right_child`, `distance` and `size`.\n\n        The `parent`, `left_child` and `right_child` are the ids of the\n        parent and child nodes in the tree. Node ids less than the number \n        of points in the original dataset represent individual points, while\n        ids greater than the number of points are clusters.\n\n        The `distance` value is the at which the child nodes merge to form\n        the parent node.\n\n        The `size` is the number of points in the `parent` node.\n

**Comment by lmcinnes** [comment]
This is definitely a bug; I'll try and get it fixed as soon as possible. I agree about numpy output ... I haven't got a function for it yet, but if that's what you want then 

clusterer.single_linkage_tree_._linkage

should be exactly the numpy array you want. Hopefully that will suffice in the meantime.

**Comment by oligilo** [comment]
Thank you so much, this is exactly what I need at the moment. I really appreciate it.

**Comment by lmcinnes** [comment]
Should all be fixed now in the repository. Sorry for the delay, but I was very busy last week with other things.

**Comment by oligilo** [comment]
Thank you, I very much appreciate it.
