### ISSUE TITLE
Can't install as hdbscan as a dependency to a package

### ISSUE THREAD

**Issue by lminer** [lmcinnes/hdbscan#26]
I'm trying to install `hdbscan` as part of a package with the command:
`virtualenv venv && source venv/bin/activate && pip install -e .`

Where `requirements.txt` contains `-e .` and `setup.py` contains:
```python
 install_requires=[
                        'cython==0.23.4',
                        'numpy==1.10.2',
                        'scikit-learn==0.17.0',
                        'hdbscan==0.7.2',
                        ...])
```

I'm getting the following error
```python
Complete output from command python setup.py egg_info:
    hdbscan/setup.py:8: UserWarning: No module named Cython.Distutils
      warnings.warn(e.message)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "hdbscan/setup.py", line 13, in <module>
        import numpy
    ImportError: No module named numpy
```
Doesn't seem to matter that pip installs cython and numpy first...

**Comment by lminer** [comment]
Looks like you need to change setup.py to be something like this: https://github.com/scipy/scipy/blob/master/setup.py#L205. The important thing is to not try to import anything for the egg_info command.

**Comment by lmcinnes** [comment]
Thanks for all the detail. I admit to having very limited expertise when it comes to python packaging -- this has been learn as I go. Based on the link it looks like this should be relatively easy to fix and I'll try to get to it as soon as I can.

**Comment by lmcinnes** [comment]
I think this was fixed? Let me know if it is still a problem.

**Comment by jordansamuels** [comment]
This seems to be a problem right now, at least for Python 3.6.   Below is a repro.  I can open up a separate issue if that works better.

```
% uname -r
3.10.0-514.16.1.el7.x86_64
% pyenv --version
pyenv 1.1.3
% virtualenv venv
Using base prefix '/home/jsamuels/.pyenv/versions/3.6.0'
New python executable in /fs/home/jsamuels/tmp/two/venv/bin/python3.6
Also creating executable in /fs/home/jsamuels/tmp/two/venv/bin/python
Installing setuptools, pip, wheel...done.
% source venv/bin/activate
(venv) % python -V
Python 3.6.0
(venv) % cat requirements.txt
numpy
hdbscan
(venv) % pip install -r requirements.txt
Collecting numpy (from -r requirements.txt (line 1))
  Downloading numpy-1.13.2-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 80kB/s
Collecting hdbscan (from -r requirements.txt (line 2))
  Using cached hdbscan-0.8.10.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/pip-build-7ld39ch0/hdbscan/setup.py:8: UserWarning: No module named 'Cython'
      warnings.warn(e.args[0])
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7ld39ch0/hdbscan/setup.py", line 13, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7ld39ch0/hdbscan/
```

**Comment by lmcinnes** [comment]
I'm travelling for the next 2 weeks so I won't be able to look into this
properly. Any chance you can use the conda package instead?

**Comment by jordansamuels** [comment]
@lmcinnes Thanks for your quick reply.  We may be able to pivot to conda as a workaround.  That does install properly - is that the (only?) recommended installation method for hdbscan at this time?

**Comment by lmcinnes** [comment]
Well the pip *ought* to work, but clearly it isn't working right now, and I
am not currently in a position to figure out why and fix it unfortunately.
I understand conda isn't necessarily the best option for you, and hopefully
we can have pip working for you again soon, but hopefully the conda package
can work as a workaround until that time. Sorry for the inconvenience.

**Comment by jordansamuels** [comment]
@lmcinnes No need to apologize!  HDBSCAN is a big win, and the code not being in a perfect state all the time is understandable.  My pythonista friends tell me that the fundamental issue here is that `setup.py` has an `import numpy` - which they recommend against.  I myself am not 100% sure how to resolve the numpy usage in `setup.py` myself; otherwise I'd issue a pull request.

**Comment by lmcinnes** [comment]
The setup.py needs to import numpy in order to find the relevant include
files to compile against, so unfortunately it's not immediately removable.
This has certainly been working historically, so I'm at a loss as to what
is causing your current issues. Pull requests would certainly be welcome if
your pythonistas can figure anything out.
