### ISSUE TITLE
Memory usage of HDBSAN for moderate large dataset (0.1 to 1 million)?

### ISSUE THREAD

**Issue by wang1943** [lmcinnes/hdbscan#27]
Hi, 

I used pip -install hdbscan on a 64-bit windows desktop in a python 2.7 environment. The packages works great with my test dataset (a few thousands of point in 3-dimensional space). However when I test on a subset of real data, ~ 50000 points, all memory (~12 GB) was occupied by python and my computer got frozen. 
Could you please help me understand what's the memory consumption with respect to data points? 

Thank you.

**Comment by lmcinnes** [comment]
I have definitely used much larger datasets successfully on machines with less memory. What's the dimensionality and properties of the dataset fed in? In certain cases hdbscan has to use fallback algorithms for which there are not good memory constraints (sparse matrix data for example).

**Comment by wang1943** [comment]
Thank you for prompt response. 
The dataset contains 3-dimentional coordinates in the shape of (n_samples, n_features) numpy array, more specific, the real dataset for test has the shape of (18068, 3). There are about 20-80 clusters in the dataset (visual inspection). The clusters are of various densities, some of them are tightly clusters while other are less dense. I was using code from the tutorial:
clusterer = hdbscan.HDBSCAN(min_cluster_size=10)
clusterer.fit(coords)
where coords is the numpy array representation of dataset.

**Comment by lmcinnes** [comment]
Something odd is going on there then, as that should be working just fine. Is the failing dataset shareable?

if you could try:

    clusterer = hdbscan.HDBSCAN(min_cluster_size=10, algorithm='prims_kdtree')
    clusterer.fit(coords)

and let me know if that makes any difference that would be a useful start if you can't share the dataset.

**Comment by wang1943** [comment]
Thank you for your suggestion. Sorry I couldn't share the real dataset with you guys. I've done some tests (all datasets were numpy array type) and here is the result:

1. using 
                 clusterer = hdbscan.HDBSCAN(min_cluster_size=10, algorithm='prims_kdtree')
                 clusterer.fit(coords)
    did solve the hugh memory consumption problem and works for both test and real datasets.
2. using 
                 clusterer = hdbscan.HDBSCAN(min_cluster_size=10)
                 clusterer.fit(coords)
    gave more complicated behavior: 
                a. it works for small simulated dataset with shape of (500, 3)
                b. it works for large simulated dataset with shape of (50000, 3)
                c. it works for a small subset of real dataset with shape (2000, 3)
                d. it **does not** work for a large subset of real dataset with shape of (18000, 3)

In case 2 d), it consumes all available memory after start parallel processing process and freeze the computer. It is difficult for me to figure out why this specific case would fail. The only difference between simulated and real datasets I could think of is the higher background noise. Could that lead to the bizarre behavior?

**Comment by lmcinnes** [comment]
The parallel processing step is involved in core distance computation under certain approaches. If the kd-tree is particularly bad something could go astray there, but it really shouldn't consume memory like that. I wonder if it is possibly related to some other issues with parallelism on windows that I've had (issue #22). Perhaps if we can allow for a single threaded approach if needed that would help -- it wouldn't fix the unexpected sudden memory use, but I don't really understand quite how or why that could be happening. I'm short of time for this right now, but hopefully Chris or John can look into solutions.

**Comment by lmcinnes** [comment]
I just pushed some new code to master that allows specifying the number of jobs for parallelism. If you have the time/opportunity I would appreciate it if you could clone and build the master branch and see if the following makes any difference for the failiing dataset:

    clusterer = hdbscan.HDBSCAN(min_cluster_size=10, core_dist_n_jobs=1)
    clusterer.fit(coords)
