### ISSUE TITLE
Install hdbscan on windows

### ISSUE THREAD

**Issue by Gudui** [lmcinnes/hdbscan#28]
Installing hdbscan on windows is really really difficult, because of the various c++ compilers which has to match your python version exactly.

Is it possible for you to create a wheel package for hdbscan for python 3.5 x64?

Created using "pip wheel hdbscan", assuming wheel and hdbscan is installed.

Thanks in advance.

**Comment by Gudui** [comment]
I've managed to create the .whl packages myself.
They can be found here. (Windows 64bit, Python 3.5 64bit)

http://www.filedropper.com/hdscandependencies

**Comment by lmcinnes** [comment]
I don't have any easy access to a windows machine unfortunately. We've been looking to see if we can figure out the best way to have binary builds for different systems, but haven't come up with anything good yet. If you would like to take on windows builds I would be more than happy to ensure you have suitable access to upload them to pypi (presuming we can arrange such a thing).

**Comment by lmcinnes** [comment]
I'm going to suggest you conda install from conda-forge at this point.
