### ISSUE TITLE
soft clustering

### ISSUE THREAD

**Issue by chongxi** [lmcinnes/hdbscan#35]
This algorithm seems very efficient and promising in my application. 

One issue: In the document is was said there is a soft clustering method that shows the membership strength, however, I only see attribute `probabilities_`. `labels_` and `outlier_scores_`.  And the probability with label -1 is always 0.

The problem is that the algo always gives lots of -1 cluster that don't belong to any clusters but clearly there are lots of points in -1 cluster should belongs to some other cluster.

**Comment by lmcinnes** [comment]
The `probabilities_` vector is the cluster membership strength; the catch is that anything assigned a label on -1 is considered noise and not in any cluster (hence the zero membership strength). If you are seeing a lot of noise points you can try playing with parameters a little. I would suggest trying a smaller min_samples value (while still specifying the min_cluster_size).

**Comment by lmcinnes** [comment]
I have now folded in an experimental soft clustering function. The relevant functions are

membership_vector
all_points_membership_vectors

See the docstrings for usage while I get documentation written. I would be keen to have some experimentation and feedback from users!
