### ISSUE TITLE
Possible error with high dimensional sparse distanse matrix

### ISSUE THREAD

**Issue by zergood** [lmcinnes/hdbscan#40]
Hi!
I am trying to use hdbscan with closeness matrix with shape (202599, 202599). 0 indicates that items are far away from each other.

Code:
```javascript
  clusterer = hdbscan.HDBSCAN(min_cluster_size=10, metric="precomputed")
  labels = clusterer.fit_predict(csr)
```

Error:
```
Traceback (most recent call last):
  File "clustering.py", line 9, in <module>
    labels = clusterer.fit_predict(csr)
  File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 667, in fit_predict
    self.fit(X)
  File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 649, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 435, in hdbscan
    gen_min_span_tree, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/memory.py", line 281, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 73, in _hdbscan_generic
    min_samples, alpha)
  File "hdbscan/_hdbscan_reachability.pyx", line 41, in hdbscan._hdbscan_reachability.mutual_reachability (hdbscan/_hdbscan_reachability.c:1564)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 644, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)```

**Comment by lmcinnes** [comment]
I think a sparse distance matrix is not actually supported (it should be, it's a valid use case). Sparse matrix input as feature vectors works, but the distance matrix its a little trickier. I believe it could be implemented, but it would be very slow on the size matrix you have -- the main difficulty is computing the core distance for each point, which involves sorting every row (or column, but I see you have a csr, so let's deal with rows). That is a lot of sorts to run, even if each is small. Let me know if you're interested and I'll try and get this implemented when I get a chance.

**Comment by lmcinnes** [comment]
I have implemented support for this now -- last changes commited to master should cover it. I can't speak for performance (I suspect it won't be super) at this time, but it shouldn't be too bad. I leaned heavily on scipy's sparse matrix csgraph minimum spanning tree implementation, so hopefully that will suffice if your distance matrix is sparse enough.

**Comment by moi90** [comment]
Does the hdbscan implementation depend on a specific sparse matrix implementation? Can I use all flavours in scipy.sparse? What about Pysparse?

**Comment by lmcinnes** [comment]
I believe (as with scikit-learn) it depends on scipy.sparse. I'm unfamiliar
with Pysparse, but hopefully there is some ability to interchange with
scipy.sparse format.

**Comment by moi90** [comment]
Thanks! Another question: Does your implementation of MST inherit the following property? "This routine uses undirected graphs as input and output. That is, if graph[i, j] and graph[j, i] are both zero, then nodes i and j do not have an edge connecting them. If either is nonzero, then the two are connected by the minimum nonzero value of the two." Or (equivalently): Is it enough to store just one direction of every edge?

**Comment by lmcinnes** [comment]
If you are using the sparse distance matrix input format (i.e. sparse matrix as ``X``,``metric='precomputed'`` then in principle yes. The catch comes that the distance matrix needs to be converted into a mutual-reachability distance matrix. That step will alter the requirement to be "If either is nonzero, then the two are connected by the maximum nonzero value of the two." because of the way things get calculated. I think you might actually also need the full symmetric matrix to compute core-distance correctly in that step, but I would have to look through the code and think a little more about that.

**Comment by moi90** [comment]
Thanks! It seems that precomputing the distance matrix for a large dataset is not the best idea...
