### ISSUE TITLE
Array of cluster components and cluster labels

### ISSUE THREAD

**Issue by mwp-tj** [lmcinnes/hdbscan#42]
Hello!

Thank you for this amazing algorithm! I am trying to transition from DBSCAN (sklearn) to this version of hdbscan. I need some help figuring out this algorithm.

Using,DBSCAN from sklearn, I can get the clustered components with db.components_. Is there any way of doing this using hdbscan?

My intention is to create a 2d array with the cluster label on one column and the components on the other. Basically, I would like to look at each data point and its relevant cluster. What is the best way of doing this using hdbscan?

Thank you!

**Comment by lmcinnes** [comment]
HDBSCAN* as implemented here (and described in the original papers) does away with the notion of border points, so every point that is clustered is a core_sample. This means that, for at least one reading of how to interpret `db.components_` as implemented in sklearn's DBSCAN you could simply write

    clusterer = hdbscan.HDBSCAN().fit(data)
    components = data[clusterer.labels_ != -1]

A minor catch with this is that being *variable density* each cluster may have a different effective epsilon value (as opposed to the single global epsilon value used for DBCSAN). I don't see this as a real issue beyond one of care in interpretation.

If you simply want to line up cluster ids with the clustered point the following recipe should suffice

    clusterer = hdbscan.HDBSCAN().fit(data)
    is_clustered = clusterer.labels_ >= 0
    clusterer_labels = clusterer.labels_[is_clustered]
    components = data[is_clustered]
    result = np.vstack([labels, components.T]).T

which should result in a 2D array with the first column the cluster label, and the remaining columns the feature values of the point assigned that cluster label.

Hopefully that's what you're looking for (or close enough to set you on your way). Let me know if I can be of more help, or describe things more clearly.
