### ISSUE TITLE
The case of unclustered data for HDBSCAN

### ISSUE THREAD

**Issue by Pantamis** [lmcinnes/hdbscan#44]
Hi,

First, thank you for this awesome implementation of HDBSCAN. It is certainly one of the best and most generic clustering algorithm and having this high performance implementation is cool with SciKit. 

My datasets are groups of large time series with the same length (between 2000 and 15000 time points and 20-200 series in a dataset). Some series are really similar and i want to regroup them. In such high dimensions and so few series, cluster are not spherical and i don''t know how many clusters there are. At first, i tried DBSCAN but i need to take count of variable density of my clusters that i saw with a dendrogram of hierarchical clustering. That's why i tried HDBSCAN now and it seems to be a good one for my problem.

However, i have datasets with only one cluster of series (at sight...) and HDBSCAN return more clusters than one. So i took a look at the implementation and i saw that you exclude the root of the `condensed_tree` so that the algorithm will never return only one cluster in your implementation.

I tried to edit it myself in the file` _hdbscan_tree.pyx` (i added the root, remplaced by zeros the NaN in births list and deleted the last child for which stability is not well-defined). I succeed to "unlock" the possibility but i experiment issues with some other datasets with several clusters for which  the results of your version HDBSCAN are correct, the results are different with mine without reason (the root cluster is not stable enough but in my version many little clusters are created).

So here is my request : is it possible for you to add a parameter to choose when to exclude the root of the `condensed_tree` or not in the evaluation of the number of clusters ? I saw that you provided classes to make some choice but it's a bit difficult to deal with stability computations in the framework. I think my request is not a big deal to code.

I will continue to work on it to make a custom version where this case is allowed because i really need it but it should be great for other to have the choice for this particular case. In my opinion, stability of the root cluster makes sense and it must be considered as the others, but i understand why enforce the clustering.

Thank you again for this so cool implementation, i can provide you what i change to add this possibility if you wish,

Best,

**Comment by lmcinnes** [comment]
See if the latest master works for you; you should now have the option `allow_single_cluster` which defaults to `False` but can be set to `True` to allow single clusters. In general the root cluster has much greater stability than anything else so tends to get picked out most of the time, so I generally would advise against this, but if you know your data then it may be what you need. Also note that I force the labelling to be the points that remain in the root cluster for it's entire lifespan, resulting in some noise points still being labelled as such. This seemed more reasonable than the alternative.

**Comment by Pantamis** [comment]
Hi,

Thank you for your quick reply.
This is perfect for me, well done !
I don't know how high is the stability of the root cluster usually but i was also in need of a criterion to say if data must be clustered or not, and I think that the stability is a good one even for that when the other ideas like gap statistic failed since it is related to the pdf of the data.

I don't get noise points labeled as cluster member in the tests I made. Typically I can have one serie among the others which has a different behavior sometimes and it is correctly indicated as noise (because it is the only one to have this behavior) even when i only have one cluster in my data. Is it what you are talking about ? 

But as I said, it is perfectly fine for me in the current state, thank you again for what you have done !

The only thing which remains is the plot of condensed tree. The root cluster is never selected as before, i saw in the code that you had to rewrite the computation of stability in Python, it is a quick change to do in the file `plots.py`, it must be the `[:-1]` line 205 that must be removed if `allow_single_cluster==True`.

**Comment by Pantamis** [comment]
I found an other problem by doing tests.

Now I understand what you said about the labeling of noise points when the root cluster is selected, I think also that it is the right things to do in this case !

But I experiment errors in the code of `do_labelling` . I didn't get really how works the `TreeUnionFind` class  but when the option `allow_single_cluster=True` is selected, you can have a KeyError when you test for large stability if more than one cluster is selected.

To fix the issue you need to change
`if allow_single_clusters and \
                tree['lambda_val'][tree['child'] == n] >= \
                    tree['lambda_val'][tree['parent'] == cluster].max():`

with 
`if len(clusters)==1 and \
                tree['lambda_val'][tree['child'] == n] >= \
                    tree['lambda_val'][tree['parent'] == cluster].max():`

It must be all right now :)

**Comment by lmcinnes** [comment]
Thanks for that. I'm a little slow as I'm on vacation and then heading to
Scipy in Austin. I'll try and get the changes you suggest folded in when I
get some time. Thanks again for the detailed responses!

**Comment by Pantamis** [comment]
No problem, for me it works with the changes so no need to worry.
Once you change it, i close this issue.

**Comment by lmcinnes** [comment]
Should be all fixed now. Thanks.
