### ISSUE TITLE
import hdbscan fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by stmax82** [lmcinnes/hdbscan#45]
Hi,

I use Anaconda on Windows 10 x64 with Python 3.4 and I installed hdbscan with:

conda install cython
conda install scikit-learn
pip install hdbscan

When I import hdbscan I get the following error:

```
[pyenv] C:\temp\lakdjfklj>ipython
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import hdbscan
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-3f1c79fb1b69> in <module>()
----> 1 import hdbscan

C:\temp\lakdjfklj\pyenv\lib\site-packages\hdbscan\__init__.py in <module>()
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage

C:\temp\lakdjfklj\pyenv\lib\site-packages\hdbscan\hdbscan_.py in <module>()
     28     check_array = check_arrays
     29
---> 30 from ._hdbscan_linkage import (single_linkage,
     31                                mst_linkage_core,
     32                                mst_linkage_core_vector,

hdbscan/_hdbscan_linkage.pyx in init hdbscan._hdbscan_linkage (hdbscan\_hdbscan_linkage.c:20689)()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte
```

**Comment by lmcinnes** [comment]
That looks rather bad! Sorry! Unfortunately I don't have access to a Windows machine to reproduce this on. Hopefully one of my colleagues can take a look at this for you. I admit that Windows has caused me all sorts of problems and I am hoping to make use of conda-forge in the future to alleviate some of these problems.

**Comment by lmcinnes** [comment]
So thanks to the wonderful people at conda-forge we may have a solution for you now. If you want to try:

    conda install -c conda-forge hdbscan

you should get a version of hdbscan that is correctly compiled against your version of windows and python, and has been tested to work. At least that's the plan. Any failures are entirely mine, and any success is entirely due to conda-forge.
