### ISSUE TITLE
Pip Fails to install

### ISSUE THREAD

**Issue by ramalhoruben** [lmcinnes/hdbscan#46]
Hi,

Linux here, Python 2.7 with the 8.1.2 version of pip!  The setup process seems to fails to find a file named: '_hdbscan_tree.c'. This happens with pip or manual install.

Any help appreciated.

**Comment by lmcinnes** [comment]
Hmm, that's novel, usually all my problems are with Windows. Let me look into what's going on and I'll get back to you.

**Comment by lmcinnes** [comment]
I downloaded directly from pip and the tar.gz for 0.8 does indeed have _hdbscan_tree.c in the hdbscan directory, and builds on my OS X laptop. I don't have access to a Linux machine just at this minute, but I would expect that if the file is there then all should be well. Do you have Cython installed? Lacking Cython, or having an old version of Cython may result in build problems.

**Comment by ramalhoruben** [comment]
Yes cython was missing; after that, installation completes sucessfully.

Thank you

**Comment by wiseman** [comment]
I had the same problem.  Cython should be declared as a dependency to fix this bug, otherwise `pip install` will fail.

**Comment by lmcinnes** [comment]
Indeed, I think the issue actually is some C files not being added to the
pip package, so I really should just update the pip package. Worth a
new/bugfix release at the very least. Thanks for the report!
