### ISSUE TITLE
min_cluster_size=1

### ISSUE THREAD

**Issue by legel** [lmcinnes/hdbscan#48]
Greetings,

First, thank you for the awesome library, I've found great success with it riding on top of a word2vec -> t-SNE pipeline for a new natural language processing project called [words2map](https://github.com/overlap-ai/words2map).  I'm just a few days from publishing about our code, but am finding suddenly an unusual response around the min_cluster_size=1 edge case.

Specifically, here is a sample from my code:
```
        print vectors
        print vectors.shape
        clusters = HDBSCAN(min_cluster_size=1).fit_predict(vectors)
```
...which generates the following:

```
[[-6.45791257 -4.44567396]
 [-6.44261124 -4.46679372]
 [ 1.56015613  2.66220251]
 [-2.85201212 -6.22262758]
 [-2.09304712 -7.14152838]
 [-1.79593637 -5.40181427]
 [-2.85714682 -6.80640389]
 [ 4.3957132   0.9440575 ]
 [ 1.81048591  1.02327832]
 [ 5.16887682  6.7110603 ]
 [ 5.37719927  6.28808868]
 [ 0.11477621 -1.11785618]
 [ 5.04218427  6.9646349 ]
 [ 5.00133672 -1.09453604]
 [ 3.72641649 -7.25523152]
 [ 4.04915813 -6.63786898]
 [ 1.2898098  -0.4886845 ]
 [ 3.83732358 -6.94612688]
 [-5.76981671 -0.61409089]
 [-4.01244246 -0.87056213]
 [ 6.22234736  0.58425667]
 [-6.04886453  3.37668561]
 [ 5.72806943  0.43197586]
 [-5.69073762 -0.53585563]
 [-6.05174687  3.38048791]
 [-6.1931812  -7.1423447 ]
 [-6.58477538 -7.32116243]
 [-2.1166777  -6.3211911 ]
 [-7.34847743 -7.71195486]
 [ 2.35076966 -0.85595291]
 [ 1.84758212  0.54659307]
 [-5.19133828  0.36389009]
 [-1.31086939 -4.1921722 ]
 [ 1.79962948  1.58228398]
 [-8.89372872 -6.65828121]]
(35, 2)
Traceback (most recent call last):
  File "clusters.py", line 47, in <module>
    compute_clusters()
  File "clusters.py", line 25, in compute_clusters
    clusters = generate_clusters(topic_names, vectors_in_2D)
  File "/home/ubuntu/words2map/words2map.py", line 202, in generate_clusters
    clusters = HDBSCAN(min_cluster_size=1).fit_predict(vectors)
  File "/home/ubuntu/miniconda/envs/words2map/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 667, in fit_predict
    self.fit(X)
  File "/home/ubuntu/miniconda/envs/words2map/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 649, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/home/ubuntu/miniconda/envs/words2map/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 469, in hdbscan
    return _tree_to_labels(X, single_linkage_tree, min_cluster_size) + (result_min_span_tree,)
  File "/home/ubuntu/miniconda/envs/words2map/lib/python2.7/site-packages/hdbscan/hdbscan_.py", line 55, in _tree_to_labels
    labels, probabilities, stabilities = get_clusters(condensed_tree, stability_dict)
  File "hdbscan/_hdbscan_tree.pyx", line 477, in hdbscan._hdbscan_tree.get_clusters (hdbscan/_hdbscan_tree.c:9977)
  File "hdbscan/_hdbscan_tree.pyx", line 520, in hdbscan._hdbscan_tree.get_clusters (hdbscan/_hdbscan_tree.c:9812)
  File "hdbscan/_hdbscan_tree.pyx", line 371, in hdbscan._hdbscan_tree.do_labelling (hdbscan/_hdbscan_tree.c:7355)
  File "hdbscan/_hdbscan_tree.pyx", line 269, in hdbscan._hdbscan_tree.TreeUnionFind.union_ (hdbscan/_hdbscan_tree.c:5911)
  File "hdbscan/_hdbscan_tree.pyx", line 284, in hdbscan._hdbscan_tree.TreeUnionFind.find (hdbscan/_hdbscan_tree.c:6127)
IndexError: index 98 is out of bounds for axis 0 with size 98
```
I don't receive any error when setting min_cluster_size=2, and am having trouble figuring out why and what I might need to do try to debug further.

Otherwise everything has been great and I am very grateful for everything; I also recall making the min_cluster_size=1 parameter work previously, and so am not sure in what way this behavior may be data-dependent...

Cheers!

**Comment by lmcinnes** [comment]
It is possible that this error may be fixed in the current master branch --
were you running that, or a version from PyPI? If the former I'll have to
look into it. In practice a min_cluster_size of 1 is inadvisable, and I
should potentially have a check on the parameter values to prevent it, but
I'll have to see.

Your project looks great by the way! I look forward to seeing and hearing
more about it!

**Comment by legel** [comment]
Thanks all around!

Indeed, I'm using the PyPi distribution,  but should have no problem going through the master branch on github instead. :)

Can you explain just a bit why min_cluster_size=1 is inadvisable? My understanding is that it would create unique cluster_ids for all of the singletons, which is the behavior I believe I'd like. Right now I need to recurse through the cluster labels and reset any -1 labels to a unique positive integer, which isn't a problem, I think, but just good to be on the same page.

PS I'm redoing a mapping of ~75 scientists and engineers we'd like to thank, and I'm going to add your name to the list as a little token of appreciation. Will post a link here for you in a bit!

**Comment by lmcinnes** [comment]
Setting min_cluster_size to 1 (particularly without setting min_samples to
something) means you are pretty much doing single linkage (albeit with a
slightly novel cluster extraction). Still it should work in master I think
-- let me know if it doesn't. Ideally I think min_cluster_size of 2 would
be more sensible, and leave the rest as "noise".

Anyway, thanks for the interest, I look forward to seeing your project!

**Comment by legel** [comment]
Got it - that makes a lot of sense. Thanks for everything. As promised:

<p style="text-align: center;"><span style="font-family:georgia,serif"><img alt="" src="https://raw.githubusercontent.com/overlap-ai/words2map/master/visualizations/tech.png" /></span></p>

We will be doing a guest post on [yhat's blog](http://blog.yhat.com/) on Friday, but here's a [sneak peak](https://medium.com/@lancelegel/word2map-high-resolution-mappings-of-any-sets-of-topics-b04a4516b9cd#.s2e0jytvj) at the story behind this, where we call HDBSCAN out. Hopefully this leads to a nice boost in energy for you. :)

**Comment by lmcinnes** [comment]
Thanks so much!

**Comment by splattner** [comment]
Still seeing this in version v0.8.2 in pypi. When do you plan to push a fixed version to pypi?

**Comment by lmcinnes** [comment]
There should be a new version available now.
