### ISSUE TITLE
Extract tree structure from clustering

### ISSUE THREAD

**Issue by tkosciol** [lmcinnes/hdbscan#55]
I'm wondering if it is possible to get a tree-like structure of the resulting clustering. What I'm ultimately trying to do is to get a dendogram overlaid on top of a heat map (e.g. seaborn.clustermap)

From looking at the source code, it seems like there's a condensed tree attribute and that there's a `_raw_tree` attribute, is that what I should be looking at?

cc @ElDeveloper

**Comment by lmcinnes** [comment]
There are a couple of tree structures. The first is the condensed tree.
This has the clusters, with points falling out of them. You might have to
do a little work to fit that with a heatmap, but it is doable. I would
suggest you use the to_pandas method to get a dataframe and understand
exactly what that data structure contains if you want to use it.

The second option is the single_linkage_tree which has a to_numpy method
that will give you exactly the same dendrogram that scipy's single linkage
clustering does (and is what seaborn uses internally in its clustermap).
That might be easier to use immediately.

I reccommend the condensed tree, but as I say you might have to work
through the details a bit to work out the best visualisation to go with a
heatmap.

**Comment by ElDeveloper** [comment]
Great, thanks so much for the explanation, this makes a lot of sense! We were planning on using seaborn, so maybe using the single_linkage_tree will be the easiest.

**Comment by lmcinnes** [comment]
I should work out how to do the condensed tree properly and add it to
seaborn with a pull request. In the meantime the single_linkage_tree should
indeed do the job.

**Comment by ElDeveloper** [comment]
Great, thanks for the info. I would be interested in hearing more about
that integration.
