### ISSUE TITLE
Problem with special input data

### ISSUE THREAD

**Issue by PHadc** [lmcinnes/hdbscan#56]
Hi, I have implemented the code successfully with the data provided by make_blobs. 
However, when I change the input data with the array [[0],[0]....[0],[20]] which are a set of 0 and a 20(noise), the output (cluster.labels_) is a set of -1 which means that the input data are all noises. 
I am wondering if there is any problem.

**Comment by Pantamis** [comment]
Did you allow a single cluster ? By default, HDBSCAN will always consider there are at least two clusters in your data : the stability of the root of the condensed tree is not calculated at all. 

But i asked recently for the option to allow the case of one single cluster : add `allow_single_cluster==True` in the constructor of the class `HDBSCAN` and it should be ok (with last version of the master branch)

**Comment by PHadc** [comment]
Thank you very much! I have noticed that parameter, but I make a stupid mistake, I changed the parameter in the Library function. Anyway, thanks very much

**Comment by lmcinnes** [comment]
I think this is good now?
