### ISSUE TITLE
Cosine Metric - Memory Error

### ISSUE THREAD

**Issue by brunoalano** [lmcinnes/hdbscan#58]
I think that I've one problem at my implementation. The `cosine` metric it's giving `Memory Error` in large datasets (60k of entries with 100 dimensions). I'm trying to investigate what is happening

**Comment by lmcinnes** [comment]
There may be a code path issue if it ends up using the generic algorithm. I
suspect what you'll need to do is check the line near the top that defines
the FAST_METRICS and add in ('arccos', 'cosine') so that it will choose to
use trees when it can.
