### ISSUE TITLE
AssertionError fitting clusters

### ISSUE THREAD

**Issue by plablo09** [lmcinnes/hdbscan#7]
I was trying your implementation with point samples (around 6,000 points) gathered from a shapefile. I read the points and transformed them to a numpy array as required by the library. When I try:

     clusterer.fit(points_sample)

I get the following error:

    Traceback (most recent call last):

      File "<ipython-input-35-c48bcd0dd0bd>", line 1, in <module>
        clusterer.fit(blobs)

      File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 489, in fit
        self._min_spanning_tree) = hdbscan(X, **self.get_params())

      File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 358, in hdbscan
        p, gen_min_span_tree)

      File "/usr/local/lib/python2.7/dist-packages/hdbscan/hdbscan_.py", line 152, in _hdbscan_large_kdtree
        assert(len(candidates) > 0)

Then I tried running the example from the [notebook](http://nbviewer.jupyter.org/github/lmcinnes/hdbscan/blob/master/notebooks/How%20HDBSCAN%20Works.ipynb) and raisng the number of samples (for simplicity, I just used the blobs). When I raised the number of samples up to 4,000 I got the exact same error.

I also tried changing the `min_cluster_size` parameter from 5 up to 50 and still get the same error (both with my data and with the blobs).

Maybe I'm failing to see something?

**Comment by lmcinnes** [comment]
No, you aren't missing anything. The catch is that (I presume) you were asking to generate the min_spanning_tree and at that size of dataset it switches to a different algorithm that doesn't properly generate the min spanning tree; I've fixed that in the github version, although soon I will hopefully be merging in the boruvka algorithm branch that will clean up a great deal of that. I'll try to git a new version to pypi up tonight. In the meantime just use gen_min_span_tree=False in the clusterer initialization.

**Comment by plablo09** [comment]
Yes, you're right, I'm using `gen_min_span_tree=True`. If I understand correctly, downloading from de repo and manually installing would fix the issue?

**Comment by lmcinnes** [comment]
Yes, that should fix the issue. Also a pip upgrade to v 0.3.1 should also resolve the problem (with the caveat that the min_spanning_tree will simply be unavailable after fitting as per the docs).
