### ISSUE TITLE
Upgrading with pip fails

### ISSUE THREAD

**Issue by plablo09** [lmcinnes/hdbscan#8]
I just tried to update to 0.4 and it fails with the following error:

    hdbscan/_hdbscan_linkage.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.

I tried on ubuntu 14.04 and OSX (El Capitan)

**Comment by lmcinnes** [comment]
Sorry about that; I'm new to distributing with pxd files and didn't get those included correctly in the first pass. Should be fixed now.

**Comment by plablo09** [comment]
Don't worry. Thanks for all the work, this implementation is awesome!
